# Generated by Django 4.0.3 on 2022-04-10 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_title', models.CharField(max_length=200)),
                ('advisory_details', models.TextField()),
                ('advisory_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('advisory_published_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
