# Generated by Django 4.0.4 on 2022-05-01 19:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='advisory_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
