# Generated by Django 4.0.4 on 2022-05-02 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_advisory_advisory_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisory',
            name='advisory_published_date',
        ),
        migrations.AddField(
            model_name='advisory',
            name='advisory_published_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
