# Generated by Django 4.0.4 on 2022-05-05 09:17

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_advisory_advisory_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_details', ckeditor.fields.RichTextField()),
                ('event_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('event_published_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
