# Generated by Django 4.0.4 on 2022-05-12 04:32

import ckeditor.fields
import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('content', '0006_advisory_tags_reallifeevent_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_title', models.CharField(max_length=200)),
                ('summary_details', ckeditor.fields.RichTextField()),
                ('summary_takeway', models.TextField()),
                ('summary_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('summary_published_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
