# Generated by Django 4.0.4 on 2022-05-13 08:54

import ckeditor.fields
import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('content', '0007_eventsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reallifeevent',
            name='event_source_url',
            field=models.URLField(default='https://localhost'),
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_event_title', models.CharField(max_length=200)),
                ('candidate_event_details', ckeditor.fields.RichTextField()),
                ('candidate_event_source_url', models.URLField(default='https://localhost')),
                ('candidate_event_published_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
