# Generated by Django 4.0.4 on 2022-05-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_reallifeevent_event_source_url_candidateevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateevent',
            unique_together={('candidate_event_title', 'candidate_event_source_url')},
        ),
    ]
