# Generated by Django 4.0.4 on 2022-05-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_candidateevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateevent',
            name='candidate_event_source_url',
            field=models.URLField(default='https://localhost', max_length=400),
        ),
        migrations.AlterField(
            model_name='reallifeevent',
            name='event_source_url',
            field=models.URLField(default='https://localhost', max_length=400),
        ),
    ]
