# Generated by Django 4.0.4 on 2022-05-15 18:33

import ckeditor.fields
import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('content', '0010_alter_candidateevent_candidate_event_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_message_title', models.CharField(max_length=200)),
                ('awareness_message_details', ckeditor.fields.RichTextField()),
                ('awareness_message_takeway', models.TextField()),
                ('awareness_message_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('awareness_message_published_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
