# Generated by Django 4.0.4 on 2022-05-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_awarenessmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='advisory_url',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='awarenessmessage',
            name='awareness_message_url',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='eventsummary',
            name='summary_url',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='reallifeevent',
            name='event_url',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
