# Generated by Django 4.0.4 on 2022-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_awarenessmessage_awareness_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenessmessage',
            name='awareness_message_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
