# Generated by Django 4.0.4 on 2022-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_awarenessmessage_awareness_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessmessage',
            name='awareness_message_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='settings.STATIC_URL/img/upload/%Y/%m/%d/'),
        ),
    ]
