# Generated by Django 4.0.4 on 2022-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_awarenessmessage_awareness_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting_event_category', models.CharField(max_length=200)),
                ('interesting_event_category_category_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
