# Generated by Django 4.0.4 on 2022-07-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_interestingeventcategory'),
        ('content', '0021_scrapedevent'),
    ]

    operations = [
    ]
