# Generated by Django 4.0.4 on 2022-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_merge_0021_interestingeventcategory_0021_scrapedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedevent',
            name='event_custom_id',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
