# Generated by Django 4.0.4 on 2022-05-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_slackinstalledworkspace_workspace_slack_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_advisory_time', models.DateTimeField(auto_now=True)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advised_workspace', to='main.slackinstalledworkspace')),
            ],
        ),
    ]
