# Generated by Django 4.0.4 on 2022-05-02 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_advisory',
            name='latest_advisory_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
