# Generated by Django 4.0.4 on 2022-05-05 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slackinstalledworkspace_workspace_joined_time'),
        ('communicator', '0002_alter_latest_advisory_latest_advisory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_advisory',
            name='advised_workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisory_informed_workspace', to='main.slackinstalledworkspace'),
        ),
        migrations.CreateModel(
            name='Latest_Event_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_event_report_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_advised_workspace', to='main.slackinstalledworkspace')),
            ],
        ),
    ]
