# Generated by Django 4.0.4 on 2022-05-07 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slackinstalledworkspace_workspace_joined_time'),
        ('content', '0005_reallifeevent'),
        ('communicator', '0003_alter_latest_advisory_advised_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_sent_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_event_notified', to='main.slackinstalledworkspace')),
                ('event_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sent_to_workspace', to='content.reallifeevent')),
            ],
        ),
        migrations.CreateModel(
            name='Advisories_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_sent_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_advisory_notified', to='main.slackinstalledworkspace')),
                ('advisory_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_sent_to_workspace', to='content.advisory')),
            ],
        ),
    ]
