# Generated by Django 4.0.4 on 2022-05-12 04:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailinglist'),
        ('content', '0007_eventsummary'),
        ('communicator', '0004_events_sent_advisories_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_summary_sent_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_event_summary_notified', to='main.slackinstalledworkspace')),
                ('event_summary_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_summary_sent_to_workspace', to='content.eventsummary')),
            ],
        ),
    ]
