# Generated by Django 4.0.4 on 2022-05-15 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_awarenessmessage'),
        ('main', '0006_mailinglist'),
        ('communicator', '0005_eventsummary_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Awareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_awareness_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awareness_advised_workspace', to='main.slackinstalledworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='Awareness_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_message_sent_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advised_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_awareness_notified', to='main.slackinstalledworkspace')),
                ('awareness_message_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awareness_message_sent_to_workspace', to='content.awarenessmessage')),
            ],
        ),
    ]
