# Generated by Django 4.0.4 on 2022-05-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_awarenessmessage_awareness_category'),
        ('communicator', '0006_latest_awareness_awareness_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_awareness',
            name='latest_awareness_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_awareness', to='content.awarenessmessage'),
        ),
    ]
