# Generated by Django 4.0.4 on 2022-05-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_slackinstalledworkspace_workspace_advisory_shout_and_more'),
        ('communicator', '0008_alter_latest_advisory_advised_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_advisory',
            name='advised_workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisory_informed_workspace', to='main.slackinstalledworkspace'),
        ),
        migrations.AlterField(
            model_name='latest_event_report',
            name='advised_workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_advised_workspace', to='main.slackinstalledworkspace'),
        ),
    ]
