# Generated by Django 4.0.4 on 2022-05-25 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_slackinstalledworkspace_workspace_advisory_shout_and_more'),
        ('communicator', '0009_alter_latest_advisory_advised_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_awareness',
            name='advised_workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awareness_advised_workspace', to='main.slackinstalledworkspace'),
        ),
    ]
