# Generated by Django 4.0.3 on 2022-04-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slackinstalledworkspace',
            unique_together={('enterprise_id', 'workspace_id')},
        ),
    ]
