# Generated by Django 4.0.3 on 2022-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_slackinstalledworkspace_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_slack_url',
            field=models.URLField(default='hla'),
            preserve_default=False,
        ),
    ]
