# Generated by Django 4.0.4 on 2022-05-02 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slackinstalledworkspace_workspace_slack_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_joined_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
