# Generated by Django 4.0.4 on 2022-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slackinstalledworkspace_workspace_joined_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_default_channel',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
    ]
