# Generated by Django 4.0.4 on 2022-05-10 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slackinstalledworkspace_workspace_default_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_list_user_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('mailing_list_joined_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
