# Generated by Django 4.0.4 on 2022-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_advisory_shout',
            field=models.CharField(choices=[('CHANNEL', '<!channel>'), ('PRESENT', '<!here>'), ('QUIET', 'All')], default='CHANNEL', max_length=7),
        ),
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_awareness_shout',
            field=models.CharField(choices=[('CHANNEL', '<!channel>'), ('PRESENT', '<!here>'), ('QUIET', 'All')], default='PRESENT', max_length=7),
        ),
        migrations.AddField(
            model_name='slackinstalledworkspace',
            name='workspace_event_shout',
            field=models.CharField(choices=[('CHANNEL', '<!channel>'), ('PRESENT', '<!here>'), ('QUIET', 'All')], default='QUIET', max_length=7),
        ),
    ]
