# Generated by Django 4.0.4 on 2022-06-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_slackinstalledworkspace_workspace_advisory_shout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_id', models.CharField(max_length=50)),
                ('admin_user_name', models.CharField(max_length=200)),
                ('admin_user_email', models.EmailField(blank=True, max_length=254)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.slackinstalledworkspace')),
            ],
        ),
    ]
